### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/vegan_delights#1]
As a **Site User**, I can **log in or log out of my account** so that **I can keep my account secure**.

# **Acceptance Criteria**

a. As a Site User I should see a "Sign Up" button on the homepage.
b. The click of the button should lead the Site User to the SignUp page.
c. After filling in the details a new account should be created for the Site User.

# **Tasks**

- [x] Add a SignUp button to the nav bar, which is only visible for logged out Site Users
- [x]  Create SignUp.html in templates
- [x]  Create success or error messages for the registration process
