### ISSUE TITLE
USER STORY: Recipe Management Admin

### ISSUE THREAD

**Issue by mehatabpathan** [mehatabpathan/vegan_delights#12]
As a **Site Administrator**, I can **create, read, update and delete categories, recipes and comments** so that **I can manage the website**.

#**Acceptance Criteria**

a. When the admin user is logged into the admin panel they can see a list of all recipes, comments and meal plan items.
b. The admin user can delete and edit any recipe, comment or meal plan item across the site.
c. The admin user can create new recipes, comments and meal plan items.

#**Tasks**

- [x]  Create Recipe, Comment and Meal plan item models to include all required fields.
- [x]  Create a superuser
- [x]  Set up Recipe, Comment and Meal Plan Item models on admin site
- [x]  Install summernote for creating recipes
